@startuml
left to right direction
actor Користувач
actor Адміністратор

Користувач --> (Реєстрація/Авторизація)
Користувач --> (Перегляд сніпетів)
Користувач --> (Створення сніпета)
Користувач --> (Редагування сніпета)
Користувач --> (Видалення сніпета)
Користувач --> (Лайк сніпета)

Адміністратор --> (Управління категоріями)
Адміністратор --> (Модерація контенту)
Адміністратор --> (Реєстрація/Авторизація)
Адміністратор --> (Перегляд сніпетів)
@enduml